Add TCP support
CypherpunkArmory/punch pull request #31
Opened 2019-06-25 22:41 UTC by AndrewScibek

Add `punch tcp` command.

This will allow users to forward tcp ports from the punch cli

2019-06-25 22:45 UTC, AndrewScibek commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add tcp support to punch](https://trello.com/c/othk5abk/463-add-tcp-support-to-punch)

2019-07-01 17:50 UTC, AndrewScibek commented
This can only forward one tcp connection. Need to refactor tunnel to fix that issue

2019-07-03 00:04 UTC, stephenprater requested changes
Looks good - I think there are probably some unit tests that we need to write for some of this stuff.  Do we want a couple of big-bang integration tests to run in this repo?  Is it possible for changes in this repo to _break_ an integration test?

2019-07-03 00:04 UTC, stephenprater commented on restapi/tunnels.go
>  	Port      []string   `jsonapi:"attr,port,omitempty"`
Why is this `Port` field distinct from the `TCPPorts` field?

2019-07-03 00:04 UTC, stephenprater commented on tunnel/ssh_jump.go
> +			Port: "3002",
so this limits you to one TCP port per tunnel - since there is no limitation on the port in the container I see two possible solution here - 1) just generate a random port it'll _probably_ be fine unless you're forwarding hundreds of ports.  2) map each forwarded port to the port in the container (so "http" becomes "80" and "https" becomes "443" etc) - This would requires an equivalent change the job definition in the API, but since we're not trying to use batch jobs anymore I don't think that's too much to do.

2019-07-03 00:04 UTC, stephenprater commented on tunnel/ssh_jump.go
> +
Is this just an infinite loop?  Will it eat cycles while it does this?  Does it need a sleep or something in the center or does `semaphore.CanRun()` block?

2019-07-03 00:04 UTC, stephenprater commented on tunnel/ssh_jump.go
> +	// FIXME:  This should be a LUT
remove this comment, I FIXDYOU

2019-07-03 00:04 UTC, stephenprater commented on tunnel/ssh_jump.go
> +		HostKeyCallback: ssh.InsecureIgnoreHostKey(),
We just need to not add it to authorized hosts I think - you shouldn't ever wind up with the same one twice I think?

2019-07-03 00:04 UTC, stephenprater commented on tunnel/tunnel.go
> +			tunnelConfig.EndpointType, tunnelConfig.EndpointURL.Host, tunnelConfig.TCPPorts[0])
This should be the _returned_ ports right?

2019-07-03 00:04 UTC, stephenprater commented on tunnel/tunnel.go
> +		outputString = fmt.Sprintf("Access your tcp endpoint at %s://tcp.%s:%s",
"Access your service at"

2019-07-03 00:04 UTC, stephenprater commented on tunnel/tunnel.go
> +			// so you need to let the listener be GC'ed by replacing it with a new object
There's a lot of wrong-ness to unpack in my comment here 😆

2019-07-03 00:04 UTC, stephenprater commented on tunnel/tunnel.go
> +			listener, _ = sClient.Listen("tcp", remoteEndpoint.String())
I'm not sure we should ignore this error.  I can't really imagine something recoverable here, but I can envision a failure putting the client into a state where it panics or gives bad feedback.

2019-07-03 00:06 UTC, AndrewScibek commented on tunnel/ssh_jump.go
> +			Port: "3002",
I think we can just use an iterator here. In the job definition i define tcp ports as such. 
ex. 3002,3003....

2019-07-03 00:09 UTC, AndrewScibek commented on tunnel/ssh_jump.go
> +
I guess we can sleep here. This is after you control c so it shouldnt be a long sleep

2019-07-03 00:11 UTC, AndrewScibek commented on restapi/tunnels.go
>  	Port      []string   `jsonapi:"attr,port,omitempty"`
Port is the type of tunnels created
TCP ports are the tcp ports being publicly forwarded.

I will rename the top port

2019-07-03 00:12 UTC, AndrewScibek commented on tunnel/tunnel.go
> +			tunnelConfig.EndpointType, tunnelConfig.EndpointURL.Host, tunnelConfig.TCPPorts[0])
This will be yes. TCPPorts is the port forwarded by holepunch

2019-07-03 00:13 UTC, AndrewScibek commented on tunnel/ssh_jump.go
> +		HostKeyCallback: ssh.InsecureIgnoreHostKey(),
This is in the container so i either need to hard code the public key or ignore the key. It is not being saved to authorized hosts locally

2019-07-03 00:15 UTC, AndrewScibek commented
> Looks good - I think there are probably some unit tests that we need to write for some of this stuff. Do we want a couple of big-bang integration tests to run in this repo? Is it possible for changes in this repo to _break_ an integration test?

Yes we should definitely have that. At least a forwarding http and tcp end-to-end test. Only change that should break that test is a change to cli input which should be _stable_ for awhile

2019-07-16 20:01 UTC, stephenprater commented on tunnel/ssh_jump.go
> +
I think if it's after a Ctrl-C it's fine - a loop will use as much CPU as possible without at least a small sleep - but that's probably okay in the case of "I'm fixing to quit."

2019-07-16 20:03 UTC, stephenprater approved these changes

2019-07-16 20:18 UTC, merged